In [20]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
%matplotlib inline

In [21]:
#train data
CBIS_train_patches = np.load(os.path.join("new_abnormal", "abnormal_train_patch.npy" ))
CBIS_train_labels = np.load(os.path.join("new_abnormal", "abnormal_train_Lbl.npy" ))
CBIS_train_FNs = np.load(os.path.join("new_abnormal", "abnormal_train_FN.npy" ))

#test data
CBIS_test_patches = np.load(os.path.join("new_abnormal", "abnormal_test_patch.npy" ))
CBIS_test_labels = np.load(os.path.join("new_abnormal", "abnormal_test_Lbl.npy" ))
CBIS_test_FNs = np.load(os.path.join("new_abnormal", "abnormal_test_FN.npy" ))



print("Abnaormal train Patches:", CBIS_train_patches.shape)
print("Abnaormal train Labels:", CBIS_train_labels.shape)
print("Abnaormal train File Names:", CBIS_train_FNs.shape)
print("\n")
print("Abnaormal test Patches:", CBIS_test_patches.shape)
print("Abnaormal test Labels:", CBIS_test_labels.shape)
print("Abnaormal test File Names:", CBIS_test_FNs.shape)

TypeError: <lambda>() got multiple values for keyword argument 'allow_pickle'

In [4]:
#combine train and test data 

CBIS_all_patches = np.concatenate([CBIS_train_patches, CBIS_test_patches], axis=0)
CBIS_all_labels = np.concatenate([CBIS_train_labels, CBIS_test_labels], axis=0)
CBIS_all_FNs = np.concatenate([CBIS_train_FNs, CBIS_test_FNs], axis=0)

CBIS_all_patches, CBIS_all_labels, CBIS_all_FNs = \
shuffle(CBIS_all_patches, CBIS_all_labels, CBIS_all_FNs, random_state=19510705)

In [5]:
#split the combined data into train and test
train_patches, test_patches, train_labels, test_labels, train_FNs, test_FNs = \
train_test_split(CBIS_all_patches, CBIS_all_labels, CBIS_all_FNs, test_size = 0.183565, random_state=19430727)

In [79]:
#train data
train_images = train_patches
train_labels = train_labels
train_FNs = train_FNs

#test data
test_images = test_patches
test_labels = test_labels
test_FNs = test_FNs

In [80]:
le = preprocessing.LabelEncoder()
le.fit(train_labels)

LabelEncoder()

In [90]:
list(le.classes_)

['BENIGN_calcification',
 'BENIGN_mass',
 'MALIGNANT_calcification',
 'MALIGNANT_mass']

In [91]:
#Convert Normal to 0 
train_labels_en = le.transform(train_labels)
#train_labels_en[train_labels_en==]=0

test_labels_en = le.transform(test_labels)
#test_labels_en[test_labels_en==5]=0

In [92]:
np.unique(train_labels_en)

array([0, 1, 2, 3], dtype=int64)

In [93]:
np.unique(test_labels_en)

array([0, 1, 2, 3], dtype=int64)

In [94]:
classes = le.classes_

In [95]:
classes

array(['BENIGN_calcification', 'BENIGN_mass', 'MALIGNANT_calcification',
       'MALIGNANT_mass'], dtype='<U23')

In [96]:
train_labels_en

array([0, 2, 1, ..., 2, 0, 0], dtype=int64)

In [97]:
train_bin_labels = np.zeros(len(train_labels_en)).astype(np.int32)
train_bin_labels[train_labels_en != 0] = 1

test_bin_labels = np.zeros(len(test_labels_en)).astype(np.int32)
test_bin_labels[test_labels_en != 0] = 1

In [98]:
np.unique(train_labels_en)

array([0, 1, 2, 3], dtype=int64)

In [99]:
np.unique(train_bin_labels)

array([0, 1])

In [100]:
np.unique(test_labels_en)

array([0, 1, 2, 3], dtype=int64)

In [101]:
np.unique(test_bin_labels)

array([0, 1])

In [103]:
np.save(os.path.join("Label", "train_labels_en.npy"), train_labels_en)
np.save(os.path.join("Label", "test_labels_en.npy"), test_labels_en)
np.save(os.path.join("Label", "train_bin_labels.npy"), train_bin_labels)
np.save(os.path.join("Label", "test_bin_labels.npy"), test_bin_labels)

In [104]:
X_val, X_test, y_val, y_test, y_val_multi, y_test_multi = \
    train_test_split(test_images, test_bin_labels, test_labels_en, test_size=0.5, random_state=19730104)
X_train, y_train, y_train_multi = \
     shuffle(train_images, train_bin_labels, train_labels_en, random_state=100)

In [108]:
np.save(os.path.join("Data", 'X_train.npy'), X_train)
np.save(os.path.join("Data", 'y_train.npy'), y_train)
np.save(os.path.join("Data", 'train_labels_multi.npy'), y_train_multi)

np.save(os.path.join("Data", 'X_val.npy'), X_val)
np.save(os.path.join("Data", 'y_val.npy'), y_val)
np.save(os.path.join("Data", 'y_val_labels_multi.npy'), y_val_multi)

np.save(os.path.join("Data", 'X_test.npy'), X_test)
np.save(os.path.join("Data", 'y_test.npy'), y_test)
np.save(os.path.join("Data", 'y_test_labels_multi.npy'), y_test_multi)